project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Data Rangers
    background: "#06402B"
    left:
      - text: Home
        href: index.qmd
      - text: Documentation
        href: documentation.qmd
      - text: Solution
        href: solution.qmd

    
    right: 
    - text: Blog
      href: blog/index.qmd
      icon: megaphone
    - icon: github
      href: https://github.com/VictorThrive/AgricConnect-PHL.git

      
format:
  html:
    theme: [cosmo, style.scss]
